Repository klerikdust/anniediscord, pull requests merged in 2020-08, with the labels that each got.

#244 small fix for weeb lb
  src/commands/server/leaderboard.js
Labels: bug

#242 file path update
  src/events/reconnecting.js
Labels: bug

#243 auto Role update
  src/config/customConfig.js
  src/libs/commands.js
  src/libs/exp.js
  src/libs/points.js
Labels: enhancement

#249 Set theme
  src/commands/user/switchingTheme.js
  src/libs/database.js
  src/locales/en.json
Labels: bug

#262 Create user_experience.md
  .github/ISSUE_TEMPLATE/user_experience.md
Labels: documentation

#265 logging for new servers fixed
  src/config/customConfig.js
  src/events/guildCreate.js
  src/events/guildDelete.js
  src/events/guildUnavailable.js
  src/libs/logs.js
Labels: bug
